# Generated by Django 5.2.1 on 2025-05-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='next',
            field=models.IntegerField(default=100),
        ),
    ]
