# Generated by Django 5.2.1 on 2025-05-23 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_next'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='next',
        ),
    ]
